version: '3.1'

services:

  db:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - ms_net
networks:
  ms_net:
    external: true
